# Generated by Django 3.2.12 on 2022-03-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_category_coupon_order_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cate',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
