# Generated by Django 3.2.12 on 2022-03-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20220326_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='xtra_price',
            field=models.IntegerField(default=0),
        ),
    ]
